### ISSUE TITLE
Bài tập 1b

### ISSUE THREAD

**Issue by vihoangson** [DeRossi/first_project#1]
# Làm lại bài tập 1

**Comment by DeRossi** [comment]
Comment nhưng gi ko hieu vao day
Ok?? - Da okie

**Comment by vihoangson** [comment]
Dùng thư viện bootstrap để giao diện đẹp hơn

**Comment by vihoangson** [comment]
Reply trong commit này.
(Link)[https://github.com/DeRossi/first_project/commit/6270ebdc6cceaf9caf14d54f559b4f1a98b8012c]

**Comment by vihoangson** [comment]
# Ngày mai sửa xong lỗi chạy đc rồi làm bài tập thứ 2 nghe, nhớ cẩn thận.
