### ISSUE TITLE
Bài tập 2

### ISSUE THREAD

**Issue by vihoangson** [DeRossi/first_project#2]
![Bai tap 2](http://gyazo.cybridge.jp/gyazo/f1/9b/e9/f19be97961316c928490342cfcd3231e.png)

**Comment by DeRossi** [comment]
em có sử dụng 1 số hàm để giải quyết như max, count, explode

**Comment by vihoangson** [comment]
Viết lại ko dùng hàm max thử xem

**Comment by DeRossi** [comment]
Da rùi anh ơi.
