### ISSUE TITLE
Bài tập 3:  Regular Expression - Bài tập căn bản

### ISSUE THREAD

**Issue by vihoangson** [DeRossi/first_project#3]
## Bài 01: Kiểm tra định dạng của thẻ cào điện thoại.

Hãy viết chuỗi Regex kiểm tra định dạng của thẻ cào điện thoại với cấu trúc như sau: xxxx-xxxx-xxxx-xxxx, trong đó x là các số từ [0-9]
## Bài 02: Kiểm tra định dạng ngày tháng năm.

Hãy kiểm tra một chuỗi có đúng định dạng ngày tháng năm hay không dd/mm/yyyy. Lưu ý là đối với ngày thì có thể từ 1 -> 31.
## Bài 03: Kiểm tra tên đăng nhập của người dùng có đúng định dạng hay không.

Hãy kiểm tra tên đăng nhập với yêu cầu:

Chữ đầu tiên không phải là số
Chiều dài trong khoảng từ 4 -> 12 ký tự
Chỉ chấp nhận các chữ số từ 0-9, chữ cái thường, chữ cái hoa và dấu gạch dưới (_)
## Bài 04: Kiểm tra định dạng mật khẩu khi đăng ký.

Hãy kiểm tra mật khẩu của người dùng khi đăng ký vì như vậy sẽ an toàn hơn.  Yêu cầu:

Mật khẩu ít nhất 8 ký tự
Phải có chữ hoa, chữ thường, số và 1 ký tự đặc biệt
## Bài 05: Kiểm tra định dạng của email

Hãy kiểm tra email người dùng nhập vào  có đúng hay không? Chỉ cần làm đơn giản ko phức tạp
## Bài 06: Kiểm tra định dạng URL

Hãy kiểm tra chuỗi URL người dùng nhập vào có đúng hay không.
## Bài 08: Lấy một đoạn ngắn trong URL.

Giả sử ta có URL như sau: http://freetuts.net/tong-quan-ve-route-trong-laravel-290.html. Hãy lấy dòng chữ tong-quan-ve-route-trong-laravel.

Lưu ý: 

Dòng chữ tong-quan-ve-route-trong-laravel động, nghĩa là nó có thể được thay thế bởi dòng chữ khác
Số 20 cũng có thể thay đổi bởi một con số khác
## Bài 09: Lấy danh sách các LINK của trang  http://freetuts.net/

Gợi ý: Các LINK sẽ nằm trong thẻ a
## Bài 10: Lấy danh sách các URL hình ảnh  của trang http://freetuts.net/codeigniter

Gợi ý: Các URL sẽ nằm trong thẻ img

**Comment by DeRossi** [comment]
Deadline : 1h trưa 4/11/2015

**Comment by DeRossi** [comment]
mấy bài này khó quá, em vẫn chưa định lượng được sức mình, @@
