### ISSUE TITLE
Lesson 4 - Array

### ISSUE THREAD

**Issue by vihoangson** [DeRossi/first_project#4]
# KTLT bài : 132 -138, 148,151,153,257,261,263

> !! Lưu ý mỗi bài là 1 funciton có input và output rõ ràng

Các bài tập về array ko dùng hàm hỗ trợ như max, sort làm nhé.

**Comment by DeRossi** [comment]
Em xong rùi, cảm ơn anh :"D

**Comment by vihoangson** [comment]
# Chú ý cái này

-Làm lại các bài 148,151,153 cho tối ưu nhất

-Các bài 257,261,263 chưa làm >.< ????

**Comment by vihoangson** [comment]
# Cái này là cái gi ?

http://gyazo.cybridge.jp/8df0233fabc0eb30012d1d34337a39de

**Comment by DeRossi** [comment]
Em đã hoàn thành 257,261,263 và tối ưu hóa code các bài 148,151,153 :8ball:
