### ISSUE TITLE
Bài tập 7 - Ma trận - Tiếp theo

### ISSUE THREAD

**Issue by vihoangson** [DeRossi/first_project#8]
# Phần 6: Xoay ma trận 1 góc 90 độ
- Tùy chỉnh trái hay phải
# Phần 7: Vẽ hình 1 - Số dòng có thể tùy chỉnh được

![](http://gyazo.cybridge.jp/gyazo/d9/45/5a/d9455a7d420d4d0abacaf875f35fe8b6.png)
# Phần 7: Vẽ hình 2 - Số dòng có thể tùy chỉnh được

![](http://gyazo.cybridge.jp/gyazo/d5/5f/3c/d55f3cef777341062fad0b1d8934b95d.png)

**Comment by DeRossi** [comment]
em hận ma trận T___T

**Comment by vihoangson** [comment]
# Làm tiếp bài này đi cho hết hận

#### Đặt tên hàm này là "đối xứng" nghe

![](http://gyazo.cybridge.jp/gyazo/1e/7d/55/1e7d555d9bbefbd0907ca8dc0fe786a6.png)

**Comment by DeRossi** [comment]
Done :+1:
